image: cosmonaut/hdf5-builder:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - apt-get -y -qq install build-essential git autoconf imagemagick doxygen pandoc pandoc-citeproc python3-numpy python3-colorama || true

stages:
  - build
  - postbuild
  - test
  - clean

# Stage "build"
build:
  stage: build
  artifacts:
    untracked: true
  tags:
    - plasma
  script:
    - ./autogen.sh
    - ./configure --enable-ieee
    - make

test:
  stage: test
  dependencies:
    - build
  tags:
    - plasma
  script:
    - make test

doc:
  stage: postbuild
  dependencies:
    - build
  tags:
    - plasma
  script:
    - make doc
  allow_failure: true
