image: debian:stretch

before_script:
  - apt-get update -y -qq
  - apt-get -y -qq install build-essential git libhdf5-100 libhdf5-dev autoconf hdf5-tools imagemagick doxygen pandoc pandoc-citeproc
  - git submodule update --init

stages:
  - build
  - deploy
  - test
  - test-ext


# Stage "build"
build:
  script:
    - ./autogen.sh
    - ./configure --enable-hdf5 --enable-ieee
    - make

deploy:
  script:
    - ./autogen.sh
    - ./configure --enable-hdf5 --enable-ieee
    - make dist RELEASE=/tmp/pdp3

test:
  script:
    - ./autogen.sh
    - ./configure --enable-hdf5 --enable-ieee
    - make test

test-ext:
  script:
    - ./autogen.sh
    - ./configure --enable-hdf5 --enable-ieee
    - make test-ext

doc:
  script:
    - ./autogen.sh
    - ./configure --enable-hdf5 --enable-ieee --with-doc-formats='html rtf'
    - make doc
