image: cosmonaut/hdf5-builder:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - apt-get -y -qq install build-essential git autoconf imagemagick doxygen pandoc pandoc-citeproc || true

stages:
  - build
  - postbuild
  - test
  - clean

# Stage "build"
build:
  stage: build
  artifacts:
    untracked: true
  tags:
    - plasma
  script:
    - ./autogen.sh
    - ./configure --enable-hdf5 --enable-ieee
    - make

test:
  stage: test
  dependencies: 
    - build
  tags:
    - plasma
  script:
    - make test

# test-ext:
#   stage: test
#   dependencies: 
#     - build
#   tags:
#     - plasma
#   script:
#     - make test-ext
#   allow_failure: true

doc:
  stage: postbuild
  dependencies: 
    - build
  tags:
    - plasma
  script:
    - make doc
  allow_failure: true

hdf5-build:
  stage: build
  tags:
    - plasma
  script:
    - ./autogen.sh
    - ./configure --enable-hdf5 --enable-ieee
    - make hdf5-install
  allow_failure: true
