image: cosmonaut/hdf5-builder:latest

before_script:
  - apt-get -y -qq install build-essential git autoconf imagemagick doxygen pandoc pandoc-citeproc || true
  - git submodule update --init

stages:
  - build
  - deploy
  - test
  - test-ext


# Stage "build"
build:
  script:
    - ./autogen.sh
    - ./configure --enable-hdf5 --enable-ieee
    - make

test:
  script:
    - ./autogen.sh
    - ./configure --enable-hdf5 --enable-ieee
    - make test

test-ext:
  script:
    - ./autogen.sh
    - ./configure --enable-hdf5 --enable-ieee
    - make test-ext

doc:
  script:
    - ./autogen.sh
    - ./configure --enable-hdf5 --enable-ieee --with-doc-formats='html rtf'
    - make doc
