image: cosmonaut/hdf5-builder:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - apt-get -y -qq install build-essential git autoconf imagemagick doxygen pandoc pandoc-citeproc || true

stages:
  - build
  - postbuild
  - test
  - clean

# Stage "build"
build:
  stage: build
  script:
    - ./autogen.sh
    - ./configure --enable-hdf5 --enable-ieee
    - make

test:
  stage: test
  script:
    - ./autogen.sh
    - ./configure --enable-hdf5 --enable-ieee
    - make test

test-ext:
  stage: test
  script:
    - ./autogen.sh
    - ./configure --enable-hdf5 --enable-ieee
    - make test-ext

doc:
  stage: postbuild
  script:
    - ./autogen.sh
    - ./configure --enable-hdf5 --enable-ieee --with-doc-formats='html rtf'
    - make doc
  allow_failure: true

clean:
  stage: clean
  script: make mrproper
  when: always

hdf5-build:
  stage: build
  script:
    - ./autogen.sh
    - ./configure --enable-hdf5 --enable-ieee
    - make hdf5-prereq
  allow_failure: true
