language: c++
sudo: required
os: linux
dist: trusty
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
    env:
      - EXPORT_VARS_CMD="export CC=gcc-7 && export CXX=g++-7"

before_install:
  - eval "${EXPORT_VARS_CMD}"

before_script:
  - echo 'Europe/Kiev' | sudo tee /etc/timezone
  - sudo dpkg-reconfigure --frontend noninteractive tzdata

script:
  - make test

after_script:
  - make mrproper
