language: c++
sudo: required
os: linux
dist: trusty
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6
      - git
    env:
      - EXPORT_VARS_CMD="export CC=gcc-7 && export CXX=g++-6"

before_install:
  - eval "${EXPORT_VARS_CMD}"

before_script:
  - echo 'Europe/Kiev' | sudo tee /etc/timezone
  - sudo dpkg-reconfigure --frontend noninteractive tzdata
  - git submodule update --init

script:
  - if [ $TRAVIS_BRANCH = 'master' ]; then make test-ext; else make test; fi

after_script:
  - make mrproper
