function p_struct = temp4

p_struct(1) = struct('internal_prop',    {struct('name',            {'electrons'},    ...
                                                 'mass',            {1},              ...
                                                 'charge',          {-1},             ...
                                                 'lambda',          {[]},             ...
                                                 'x_interact_type', {'reflection'},   ...
                                                 'y_interact_type', {'cycling'}                                                        )},...
                     'init_load_param',  {struct('spatial_fun',     {struct('handle',{@homogene_fun}, 'param',{1.0*[1.0e16 1.0e16]})}, ... 
                                                 'velocity_fun',    {struct('handle',{[]}, 'param',{[0.5]})},                        ...
                                                 'load_type',       {'random'}, ...
                                                 'n_p',             {14e5},      ...
                                                 'n_p_max',         {14e5}                                                              )});
                                             